version: '3.8'
services:
  frontendapplication:
    container_name: chatui
    build:
      context: ./Copilot Frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
  chatmanagement:
    container_name: chatbackend
    build:
      context: ./CopilotBackend
      dockerfile: Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Production"  
    ports:
      - 44373:80
    restart: always
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    container_name: mongo
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - "./MongoDB:/data/db"    