version: "3"
services:
  julia:
    image: julia
    volumes:
      - ./files:/disk
      - ./library:/root/.julia
    working_dir: /disk
    command: ["sleep","infinity"]

# docker run --it --rm -v ${PWD}:/data -w "/data" julia julia