version: "3.3"
services:
  hindalcobot:
    container_name: hindalcobotSql
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Production"  
    ports:
      - 8080:80
    depends_on:
      - qdrant
    restart: always

#  nginx:
#    container_name: nginx
#    image: nginx:stable-alpine
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro #/etc/nginx/nginx.conf
#      - ./nginx/ssl:/etc/nginx/ssl  # Mount the directory containing your SSL file
#    ports:
#      - 443:443
#    restart: always   
#    depends_on:
#      - hindalcobot

  qdrant:
    container_name: qdarantForHindalco
    image: qdrant/qdrant:latest
    ports:
      - 6500:6333
    volumes:
      - ./Qdrant:/qdrant/storage

#TO RUN ONLY THE SqlServer USE THE FOLLOWING COMMAND
# docker run -d --name mssql  -e ACCEPT_EULA=Y -e MSSQL_SA_PASSWORD=CEleb@L_TECH -p 1433:1433 -v "$(pwd)/DatabaseLayer/data/:/var/opt/mssql/data/" -v "$(pwd)/DatabaseLayer/log/:/var/opt/mssql/log/" -v "$(pwd)/DatabaseLayer/secrets/:/var/opt/mssql/secrets/" mcr.microsoft.com/mssql/server:2022-latest